release: false

# debug info warn err
log:
  path: ./logs/app.log #日志文件路径
  level: debug # 日志级别 debug/info/warn/error
  maxbackups: 24 #保存的文件个数
  maxage: 7 #日志文件保留时长(天)
  servername: gateway

# etcd
etcd:
  addrs:
    - "etcd:2379"

# kafka
kafka:
  addrs:
    - "b-1.go-uat-2021.wc5zvs.c3.kafka.cn-north-1.amazonaws.com.cn:9092"
    - "b-2.go-uat-2021.wc5zvs.c3.kafka.cn-north-1.amazonaws.com.cn:9092"

#redis
redis:
  addrs: "gouat-20210303.v0iuxc.ng.0001.cnn1.cache.amazonaws.com.cn:6379"
  password: ""
  maxidleconns: 100
  maxopenconns: 100
  maxlifetime: 100

# trace
trace:
  addr: "jaeger:6831"

# micro注册到注册中心的配置
micro:
  registerTTL: 3 # 超时时间(秒)
  registerInterval: 1 # 注册间隔(秒)
  version: "latest"